import 'package:digify_hr_system/core/constants/app_colors.dart';
import 'package:digify_hr_system/core/localization/l10n/app_localizations.dart';
import 'package:digify_hr_system/gen/assets.gen.dart';

import 'dashboard_button_model.dart';

List<DashboardButton> getDashboardButtons(AppLocalizations loc) {
  return [
    DashboardButton(
      id: 'job-schedules',
      icon: Assets.icons.timeManagementMainIcon.path,
      label: 'Job Schedules',
      color: AppColors.dashJobSchedules,
      route: '/job-schedules',
    ),
    DashboardButton(
      id: 'employee-ss',
      icon: Assets.icons.managementIconDepartment.path,
      label: 'Employee Self-\nService',
      color: AppColors.primary,
      route: '/employee-ss',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'manager-ss',
      icon: Assets.icons.employeesCountIcon.path,
      label: 'Manager Self-\nService',
      color: AppColors.dashManagerSS,
      route: '/manager-ss',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'dashboard',
      icon: Assets.icons.dashboardMainIcon.path,
      label: loc.dashboard,
      color: AppColors.primaryLight,
      route: '/dashboard',
    ),
    DashboardButton(
      id: 'employees',
      icon: Assets.icons.employeesCountIcon.path,
      label: 'Employee\nManagement',
      color: AppColors.statIconGreen,
      route: '/employees',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'hr-ops',
      icon: Assets.icons.departmentsSmallIcon.path,
      label: 'HR Operations',
      color: AppColors.dashHROps,
      route: '/hr-ops',
    ),
    DashboardButton(
      id: 'recruitment',
      icon: Assets.icons.searchDepartmentIcon.path,
      label: 'Recruitment',
      color: AppColors.dashRecruitment,
      route: '/recruitment',
    ),
    DashboardButton(
      id: 'time-management',
      icon: Assets.icons.timeManagementMainIcon.path,
      label: 'Time\nManagement',
      color: AppColors.statIconOrange,
      route: '/time-management',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'leave-management',
      icon: Assets.icons.leaveManagementMainIcon.path,
      label: 'Leave\nManagement',
      color: AppColors.dashLeaveManagement,
      route: '/leave-management',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'attendance',
      icon: Assets.icons.timeManagementMainIcon.path,
      label: loc.attendance,
      color: AppColors.dashAttendance,
      route: '/attendance',
    ),
    DashboardButton(
      id: 'payroll',
      icon: Assets.icons.websiteIcon.path,
      label: loc.payroll,
      color: AppColors.dashPayroll,
      route: '/payroll',
    ),
    DashboardButton(
      id: 'compensation',
      icon: Assets.icons.gradeIcon.path,
      label: 'Compensation',
      color: AppColors.dashCompensation,
      route: '/compensation',
    ),
    DashboardButton(
      id: 'compliance',
      icon: Assets.icons.payrollMainIcon.path,
      label: loc.compliance,
      color: AppColors.dashCompliance,
      route: '/compliance',
    ),
    DashboardButton(
      id: 'workforce-structure',
      icon: Assets.icons.workforceStructureIcon.path,
      label: 'Workforce\nStructure',
      color: AppColors.dashWorkforceStructure,
      route: '/workforce-structure',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'enterprise-structure',
      icon: Assets.icons.workforceStructureMainIcon.path,
      label: 'Enterprise\nStructure',
      color: AppColors.dashEnterpriseStructure,
      route: '/enterprise-structure',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'reports',
      icon: Assets.icons.sectionIconPurple.path,
      label: loc.reports,
      color: AppColors.dashReports,
      route: '/reports',
    ),
    DashboardButton(
      id: 'eos-calculator',
      icon: Assets.icons.reportsMainIcon.path,
      label: loc.eosCalculator,
      color: AppColors.dashEOSCalculator,
      route: '/eos-calculator',
    ),
    DashboardButton(
      id: 'government-forms',
      icon: Assets.icons.eosCalculatorMainIcon.path,
      label: 'Government\nForms',
      color: AppColors.dashGovernmentForms,
      route: '/government-forms',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'dei-dashboard',
      icon: Assets.icons.industryIcon.path,
      label: loc.deiDashboard,
      color: AppColors.dashDEIDashboard,
      route: '/dei-dashboard',
    ),
    DashboardButton(
      id: 'finance',
      icon: Assets.icons.websiteIcon.path,
      label: 'Finance',
      color: AppColors.dashFinance,
      route: '/finance',
    ),
    DashboardButton(
      id: 'supply-chain',
      icon: Assets.icons.supplyChain.path,
      label: 'Supply Chain',
      color: AppColors.dashSupplyChain,
      route: '/supply-chain',
    ),
    DashboardButton(
      id: 'module-catalogue',
      icon: Assets.icons.moduleCatalogueIcon.path,
      label: 'Module\nCatalogue',
      color: AppColors.dashModuleCatalogue,
      route: '/module-catalogue',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'product-intro',
      icon: Assets.icons.moduleCatalogueMainIcon.path,
      label: 'Product\nIntroduction',
      color: AppColors.dashProductIntro,
      route: '/product-intro',
      isMultiLine: true,
    ),
    DashboardButton(
      id: 'page-preview',
      icon: Assets.icons.sectionIconPurple.path,
      label: 'Page Preview',
      color: AppColors.dashPagePreview,
      route: '/page-preview',
    ),
    DashboardButton(
      id: 'settings',
      icon: Assets.icons.manageEnterpriseIcon.path,
      label: loc.settings,
      color: AppColors.dashSettings,
      route: '/settings',
    ),
  ];
}
